name: Continuous intregration of Recipe CO2 Estimator app
on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.13
        uses: actions/setup-python@v5
        with:
          python-version: 3.13
          cache: "poetry"
      - name: Install and configure Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.5
          virtualenvs-create: true
          virtualenvs-in-project: true
      - name: Install dependencies
        run: |
          make install
      - name: Check linting
        run: |
          make lint
      - name: Format code
        run: |
          make format
      - name: Run type checking
        run: |
          make type-check
